### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by josephgupkim** [FarzaanaM/teacozy#1]
When a different user downloads your project to use, they cannot access paths such as "User/farzaanamaliet/Desktop/BuildWebsites" because those files are on your computer and not theirs.
Try using relative paths instead of absolute paths so that I and others can view your project properly because right now no styles or images are showing up.

https://github.com/FarzaanaM/teacozy/blob/master/teacozy/index.html#L4

**Comment by FarzaanaM** [comment]
Thank you for the feedback. Will keep it mind for the next project.
